[airtable]
api_key = "pateVIsGzRlPnFTwy.54069fdc084c3843b8389e829f085cd65f8affe6150c3f05f67563d09a5c6562"  
base_id = "appNUcPhsFZOhPEis/tbl03cpCP8tw33XlV/viw7YP078eiAAB9mM?blocks=hide"          
table_name = "مؤشرات الاداء"
